import type { CommerceErrorCode } from "./contracts";

export type CommerceHttpStatus = 400 | 404 | 409 | 422 | 429 | 500 | 503;

const COMMERCE_ERROR_HTTP_STATUS = {
  INVALID_CART: 400,
  INVALID_GIFT_SELECTION: 400,
  INVALID_INPUT: 400,
  PRODUCT_NOT_FOUND: 404,
  DISCOUNT_NOT_FOUND: 404,
  DISCOUNT_INACTIVE: 422,
  DISCOUNT_NOT_STARTED: 422,
  DISCOUNT_EXPIRED: 422,
  DISCOUNT_MIN_SUBTOTAL: 422,
  DISCOUNT_USAGE_LIMIT: 409,
  QUOTE_NOT_FOUND: 404,
  QUOTE_EXPIRED: 409,
  QUOTE_CHANGED: 409,
  IDEMPOTENCY_CONFLICT: 409,
  LEAD_TIME_NOTICE_REQUIRED: 422,
  RATE_LIMITED: 429,
  ORDER_CREATION_FAILED: 500,
  SHIPPING_CONFIGURATION_PENDING: 503,
  PRICING_UNAVAILABLE: 503,
} as const satisfies Record<CommerceErrorCode, CommerceHttpStatus>;

export function commerceErrorHttpStatus(code: CommerceErrorCode): CommerceHttpStatus {
  return COMMERCE_ERROR_HTTP_STATUS[code];
}
