create extension if not exists pgcrypto with schema extensions;

create table public.commerce_settings (
  singleton boolean primary key default true check (singleton),
  quote_validity_minutes integer not null check (quote_validity_minutes = 15),
  free_shipping_min_items integer not null check (free_shipping_min_items > 0),
  large_order_threshold_items integer not null check (large_order_threshold_items >= 13),
  locker_price integer not null check (locker_price >= 0),
  courier_price integer not null check (courier_price >= 0),
  pricing_policy_version text not null,
  locker_rule_version text not null,
  courier_rule_version text not null,
  terms_version text not null,
  large_order_notice text not null,
  large_order_notice_version text not null
);

insert into public.commerce_settings (
  quote_validity_minutes, free_shipping_min_items, large_order_threshold_items,
  locker_price, courier_price, pricing_policy_version, locker_rule_version,
  courier_rule_version, terms_version, large_order_notice, large_order_notice_version
) values (
  15, 6, 26, 1649, 1949, 'mvp-general-promotions-v2', 'inpost-locker-v1',
  'inpost-courier-v1', 'mvp-2026-09-14',
  'To duże zamówienie. Termin realizacji może się wydłużyć. Napisz do nas mailowo lub na Instagramie, albo poczekaj na kontakt po złożeniu zamówienia.',
  'large-order-v1'
);

create table public.checkout_quotes (
  id uuid primary key default gen_random_uuid(),
  input_items jsonb not null,
  input_gifts jsonb not null default '[]'::jsonb,
  delivery_method text not null check (delivery_method in ('inpost_locker', 'courier')),
  quote jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  constraint checkout_quotes_expiry_check check (expires_at = created_at + interval '15 minutes')
);

alter table public.orders
  drop constraint if exists orders_status_check;

update public.orders set status = 'pending_payment' where status = 'pending';

alter table public.orders
  alter column status set default 'pending_payment',
  alter column items drop not null,
  alter column shipping_address drop not null,
  add column if not exists quote_id uuid,
  add column if not exists delivery_method text,
  add column if not exists parcel_size text,
  add column if not exists pricing_policy_version text,
  add column if not exists shipping_rule_version text,
  add column if not exists shipping_total integer not null default 0,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists phone text,
  add column if not exists guest_token_hash text,
  add column if not exists idempotency_key text,
  add column if not exists checkout_payload_hash text,
  add column if not exists accepted_terms_version text,
  add column if not exists accepted_terms_at timestamptz,
  add column if not exists accepted_lead_time_notice_version text,
  add column if not exists accepted_lead_time_notice_at timestamptz,
  add column if not exists invoice_requested boolean not null default false,
  add column if not exists invoice_company_name text,
  add column if not exists invoice_nip text,
  add column if not exists invoice_email text,
  add column if not exists invoice_address_line1 text,
  add column if not exists invoice_address_line2 text,
  add column if not exists invoice_postal_code text,
  add column if not exists invoice_city text,
  add column if not exists invoice_country_code text;

alter table public.orders
  drop constraint if exists orders_quote_id_fkey;

alter table public.orders
  add constraint orders_status_check check (status in ('pending_payment', 'paid', 'processing', 'shipped', 'completed', 'cancelled', 'expired')),
  add constraint orders_order_number_key unique (order_number),
  add constraint orders_idempotency_key_key unique (idempotency_key),
  add constraint orders_checkout_quote_fkey foreign key (quote_id) references public.checkout_quotes(id),
  add constraint orders_invoice_shape_check check (
    (not invoice_requested and invoice_company_name is null and invoice_nip is null and invoice_email is null
      and invoice_address_line1 is null and invoice_address_line2 is null and invoice_postal_code is null
      and invoice_city is null and invoice_country_code is null)
    or
    (invoice_requested and invoice_company_name is not null and invoice_nip ~ '^\d{10}$' and invoice_address_line1 is not null
      and invoice_postal_code ~ '^\d{2}-\d{3}$' and invoice_city is not null and invoice_country_code = 'PL')
  );

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  merchandise_id text not null,
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  discount_total integer not null default 0 check (discount_total >= 0),
  line_total integer not null check (line_total >= 0),
  is_gift boolean not null default false,
  components jsonb not null default '[]'::jsonb
);

create table public.order_deliveries (
  order_id uuid primary key references public.orders(id) on delete cascade,
  method text not null check (method in ('inpost_locker', 'courier')),
  price integer not null check (price >= 0),
  rule_version text not null,
  parcel_size text not null check (parcel_size in ('S', 'M', 'L')),
  point_id text,
  address_line1 text,
  address_line2 text,
  postal_code text,
  city text,
  country_code text,
  constraint order_deliveries_shape_check check (
    (method = 'inpost_locker' and point_id is not null and address_line1 is null)
    or
    (method = 'courier' and point_id is null and address_line1 is not null and postal_code ~ '^\d{2}-\d{3}$' and city is not null and country_code = 'PL')
  )
);

create table public.checkout_rate_limits (
  id bigint generated always as identity primary key,
  operation text not null check (operation in ('quote', 'checkout', 'status')),
  request_fingerprint text not null,
  created_at timestamptz not null default now()
);

create index checkout_rate_limits_lookup_idx
  on public.checkout_rate_limits (operation, request_fingerprint, created_at desc);
create index checkout_quotes_expiry_idx on public.checkout_quotes (expires_at);
create index order_items_order_idx on public.order_items (order_id);
create index orders_guest_token_hash_idx on public.orders (guest_token_hash);

alter table public.commerce_settings enable row level security;
alter table public.checkout_quotes enable row level security;
alter table public.order_items enable row level security;
alter table public.order_deliveries enable row level security;
alter table public.checkout_rate_limits enable row level security;

revoke all on public.commerce_settings, public.checkout_quotes, public.orders,
  public.order_items, public.order_deliveries, public.checkout_rate_limits from anon, authenticated;
grant all on public.commerce_settings, public.checkout_quotes, public.orders,
  public.order_items, public.order_deliveries, public.checkout_rate_limits to service_role;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.commerce_rate_limit(
  p_operation text,
  p_request_fingerprint text,
  p_limit integer,
  p_window interval
) returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_request_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'INVALID_INPUT';
  end if;
  perform pg_advisory_xact_lock(hashtext(p_operation || ':' || p_request_fingerprint));
  if (select count(*) from public.checkout_rate_limits
      where operation = p_operation and request_fingerprint = p_request_fingerprint
      and created_at > now() - p_window) >= p_limit then
    raise exception using errcode = 'P0001', message = 'RATE_LIMITED';
  end if;
  insert into public.checkout_rate_limits (operation, request_fingerprint)
  values (p_operation, p_request_fingerprint);
end;
$$;

create or replace function private.commerce_build_quote(
  p_items jsonb,
  p_gifts jsonb,
  p_delivery_method text,
  p_created_at timestamptz
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  settings public.commerce_settings%rowtype;
  entry jsonb;
  product record;
  quantity integer;
  unit_gross integer;
  line_total integer;
  physical_per_unit integer;
  physical_total integer := 0;
  subtotal integer := 0;
  gift_quantity integer := 0;
  earned_gifts integer;
  shipping integer;
  items jsonb := '[]'::jsonb;
  gifts jsonb := '[]'::jsonb;
  gift_options jsonb;
begin
  select * into strict settings from public.commerce_settings where singleton;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50
    or jsonb_typeof(coalesce(p_gifts, '[]'::jsonb)) <> 'array'
    or p_delivery_method not in ('inpost_locker', 'courier') then
    raise exception using errcode = 'P0001', message = 'INVALID_CART';
  end if;

  for entry in select value from jsonb_array_elements(p_items) loop
    if coalesce(entry->>'merchandiseId', '') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      or coalesce(entry->>'quantity', '') !~ '^\d{1,2}$' then
      raise exception using errcode = 'P0001', message = 'INVALID_CART';
    end if;
    quantity := (entry->>'quantity')::integer;
    if quantity < 1 or quantity > 99 then raise exception using errcode = 'P0001', message = 'INVALID_CART'; end if;

    select id, name, type, price into product from public.products
      where id = (entry->>'merchandiseId')::uuid and status = 'published'
        and type in ('product', 'variant', 'bundle') and price is not null;
    if not found then raise exception using errcode = 'P0001', message = 'PRODUCT_NOT_FOUND'; end if;

    unit_gross := round(product.price * 1.23)::integer;
    line_total := unit_gross * quantity;
    if product.type = 'bundle' then
      select coalesce(sum(bundle_quantity), 1)::integer into physical_per_unit
      from public.products where parent_id = product.id and type = 'bundle_item' and status = 'published';
    else
      physical_per_unit := 1;
    end if;
    physical_total := physical_total + physical_per_unit * quantity;
    subtotal := subtotal + line_total;
    items := items || jsonb_build_array(jsonb_build_object(
      'merchandiseId', product.id::text, 'quantity', quantity, 'name', product.name,
      'kind', case when product.type = 'bundle' then 'bundle' else 'product' end,
      'physicalItemCount', physical_per_unit * quantity,
      'unitPriceGrosze', unit_gross, 'unitNetPriceGrosze', product.price,
      'lineSubtotalGrosze', line_total, 'discountGrosze', 0, 'lineTotalGrosze', line_total,
      'components', jsonb_build_array(jsonb_build_object(
        'merchandiseId', product.id::text, 'name', product.name, 'quantity', quantity,
        'baseAmountGrosze', line_total, 'discountGrosze', 0, 'paidAmountGrosze', line_total
      ))
    ));
  end loop;

  earned_gifts := case when physical_total >= 24 then 3 when physical_total >= 12 then 1 else 0 end;
  for entry in select value from jsonb_array_elements(coalesce(p_gifts, '[]'::jsonb)) loop
    if coalesce(entry->>'merchandiseId', '') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      or coalesce(entry->>'quantity', '') !~ '^\d{1,2}$' then
      raise exception using errcode = 'P0001', message = 'INVALID_GIFT_SELECTION';
    end if;
    quantity := (entry->>'quantity')::integer;
    gift_quantity := gift_quantity + quantity;
    select id, name into product from public.products
      where id = (entry->>'merchandiseId')::uuid and status = 'published' and type in ('product', 'variant');
    if not found or quantity < 1 then raise exception using errcode = 'P0001', message = 'INVALID_GIFT_SELECTION'; end if;
    gifts := gifts || jsonb_build_array(jsonb_build_object(
      'merchandiseId', product.id::text, 'name', product.name, 'quantity', quantity,
      'unitPriceGrosze', 0, 'lineTotalGrosze', 0
    ));
  end loop;
  if gift_quantity > earned_gifts then raise exception using errcode = 'P0001', message = 'INVALID_GIFT_SELECTION'; end if;

  select coalesce(jsonb_agg(jsonb_build_object('merchandiseId', id::text, 'name', name) order by name), '[]'::jsonb)
    into gift_options from public.products where status = 'published' and type in ('product', 'variant');
  shipping := case when physical_total >= settings.free_shipping_min_items then 0
    when p_delivery_method = 'inpost_locker' then settings.locker_price else settings.courier_price end;

  return jsonb_build_object(
    'items', items, 'subtotalGrosze', subtotal, 'discountGrosze', 0,
    'delivery', jsonb_build_object(
      'method', p_delivery_method, 'parcelSize', 'S', 'priceGrosze', shipping,
      'ruleVersion', case when p_delivery_method = 'inpost_locker' then settings.locker_rule_version else settings.courier_rule_version end
    ),
    'totalGrosze', subtotal + shipping, 'currency', 'PLN', 'createdAt', p_created_at,
    'expiresAt', p_created_at + make_interval(mins => settings.quote_validity_minutes),
    'physicalItemCount', physical_total,
    'giftPromotion', jsonb_build_object('earnedQuantity', earned_gifts, 'selectedItems', gifts, 'options', gift_options),
    'pricingPolicyVersion', settings.pricing_policy_version,
    'adjustments', case when shipping = 0 then jsonb_build_array(jsonb_build_object(
      'type', 'free_shipping', 'policyId', 'free-shipping-from-6-moulds',
      'amountGrosze', case when p_delivery_method = 'inpost_locker' then settings.locker_price else settings.courier_price end
    )) else '[]'::jsonb end,
    'requiresLeadTimeConfirmation', physical_total > settings.large_order_threshold_items,
    'leadTimeNotice', case when physical_total > settings.large_order_threshold_items then settings.large_order_notice end,
    'leadTimeNoticeVersion', case when physical_total > settings.large_order_threshold_items then settings.large_order_notice_version end
  );
end;
$$;

create or replace function public.create_checkout_quote(
  p_items jsonb,
  p_gifts jsonb,
  p_delivery_method text,
  p_request_fingerprint text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  quote_id uuid := gen_random_uuid();
  created_at timestamptz := now();
  quote jsonb;
begin
  perform private.commerce_rate_limit('quote', p_request_fingerprint, 30, interval '10 minutes');
  quote := private.commerce_build_quote(p_items, p_gifts, p_delivery_method, created_at);
  quote := quote || jsonb_build_object('id', quote_id::text);
  insert into public.checkout_quotes (id, input_items, input_gifts, delivery_method, quote, created_at, expires_at)
  values (quote_id, p_items, coalesce(p_gifts, '[]'::jsonb), p_delivery_method, quote, created_at, created_at + interval '15 minutes');
  return quote;
end;
$$;

create or replace function private.is_valid_polish_nip(p_nip text) returns boolean
language sql immutable strict set search_path = ''
as $$
  select p_nip ~ '^\d{10}$' and (
    substring(p_nip,1,1)::int * 6 + substring(p_nip,2,1)::int * 5 +
    substring(p_nip,3,1)::int * 7 + substring(p_nip,4,1)::int * 2 +
    substring(p_nip,5,1)::int * 3 + substring(p_nip,6,1)::int * 4 +
    substring(p_nip,7,1)::int * 5 + substring(p_nip,8,1)::int * 6 +
    substring(p_nip,9,1)::int * 7
  ) % 11 = substring(p_nip,10,1)::int
$$;

create or replace function public.finalize_guest_order(
  p_quote_id uuid,
  p_customer jsonb,
  p_delivery jsonb,
  p_invoice jsonb,
  p_accepted_terms_version text,
  p_accepted_lead_time_notice_version text,
  p_idempotency_key text,
  p_payload_hash text,
  p_guest_token_hash text,
  p_request_fingerprint text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  stored_quote public.checkout_quotes%rowtype;
  current_quote jsonb;
  existing public.orders%rowtype;
  created public.orders%rowtype;
  settings public.commerce_settings%rowtype;
  item jsonb;
  invoice_requested boolean := p_invoice is not null and p_invoice <> 'null'::jsonb;
begin
  if p_idempotency_key !~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' or p_payload_hash !~ '^[0-9a-f]{64}$'
    or p_guest_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'INVALID_INPUT';
  end if;

  perform pg_advisory_xact_lock(hashtext('checkout-idempotency:' || p_idempotency_key));
  select * into existing from public.orders where idempotency_key = p_idempotency_key;
  if found then
    if existing.checkout_payload_hash <> p_payload_hash or existing.quote_id <> p_quote_id
      or existing.guest_token_hash <> p_guest_token_hash then
      raise exception using errcode = 'P0001', message = 'IDEMPOTENCY_CONFLICT';
    end if;
    return jsonb_build_object(
      'orderId', existing.id::text, 'orderNumber', 'MON-' || lpad(existing.order_number::text, 6, '0'),
      'orderDisposition', 'reused', 'orderStatus', existing.status
    );
  end if;

  perform private.commerce_rate_limit('checkout', p_request_fingerprint, 5, interval '10 minutes');
  select * into stored_quote from public.checkout_quotes where id = p_quote_id for update;
  if not found then raise exception using errcode = 'P0001', message = 'QUOTE_NOT_FOUND'; end if;
  if stored_quote.expires_at <= now() then raise exception using errcode = 'P0001', message = 'QUOTE_EXPIRED'; end if;
  if stored_quote.consumed_at is not null then raise exception using errcode = 'P0001', message = 'IDEMPOTENCY_CONFLICT'; end if;

  current_quote := private.commerce_build_quote(stored_quote.input_items, stored_quote.input_gifts, stored_quote.delivery_method, stored_quote.created_at);
  current_quote := current_quote || jsonb_build_object('id', stored_quote.id::text);
  if current_quote <> stored_quote.quote then raise exception using errcode = 'P0001', message = 'QUOTE_CHANGED'; end if;

  select * into strict settings from public.commerce_settings where singleton;
  if p_accepted_terms_version <> settings.terms_version
    or coalesce(p_customer->>'email','') !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or nullif(btrim(p_customer->>'firstName'),'') is null
    or nullif(btrim(p_customer->>'lastName'),'') is null
    or regexp_replace(coalesce(p_customer->>'phone',''), '\D', '', 'g') !~ '^\d{9,15}$'
    or p_delivery->>'method' <> stored_quote.delivery_method then
    raise exception using errcode = 'P0001', message = 'INVALID_INPUT';
  end if;
  if stored_quote.delivery_method = 'inpost_locker' and nullif(btrim(p_delivery->>'pointId'),'') is null then
    raise exception using errcode = 'P0001', message = 'INVALID_INPUT';
  end if;
  if stored_quote.delivery_method = 'courier' and (
    nullif(btrim(p_delivery#>>'{address,line1}'),'') is null or p_delivery#>>'{address,postalCode}' !~ '^\d{2}-\d{3}$'
    or nullif(btrim(p_delivery#>>'{address,city}'),'') is null or p_delivery#>>'{address,countryCode}' <> 'PL'
  ) then raise exception using errcode = 'P0001', message = 'INVALID_INPUT'; end if;

  if (stored_quote.quote->>'requiresLeadTimeConfirmation')::boolean
    and p_accepted_lead_time_notice_version is distinct from stored_quote.quote->>'leadTimeNoticeVersion' then
    raise exception using errcode = 'P0001', message = 'LEAD_TIME_NOTICE_REQUIRED';
  end if;
  if invoice_requested and (
    nullif(btrim(p_invoice->>'companyName'),'') is null
    or not private.is_valid_polish_nip(p_invoice->>'nip')
    or nullif(btrim(p_invoice#>>'{address,line1}'),'') is null
    or p_invoice#>>'{address,postalCode}' !~ '^\d{2}-\d{3}$'
    or nullif(btrim(p_invoice#>>'{address,city}'),'') is null
    or p_invoice#>>'{address,countryCode}' <> 'PL'
  ) then raise exception using errcode = 'P0001', message = 'INVALID_INPUT'; end if;

  insert into public.orders (
    email, status, items, shipping_address, subtotal, discount_total, total, currency,
    delivery_method, parcel_size, pricing_policy_version, shipping_rule_version, shipping_total,
    quote_id, first_name, last_name, phone, guest_token_hash, idempotency_key, checkout_payload_hash,
    accepted_terms_version, accepted_terms_at, accepted_lead_time_notice_version,
    accepted_lead_time_notice_at, invoice_requested, invoice_company_name, invoice_nip, invoice_email,
    invoice_address_line1, invoice_address_line2, invoice_postal_code, invoice_city, invoice_country_code
  ) values (
    lower(p_customer->>'email'), 'pending_payment', stored_quote.quote->'items', p_delivery,
    (stored_quote.quote->>'subtotalGrosze')::integer, (stored_quote.quote->>'discountGrosze')::integer,
    (stored_quote.quote->>'totalGrosze')::integer, 'PLN', stored_quote.delivery_method,
    stored_quote.quote#>>'{delivery,parcelSize}', stored_quote.quote->>'pricingPolicyVersion',
    stored_quote.quote#>>'{delivery,ruleVersion}', (stored_quote.quote#>>'{delivery,priceGrosze}')::integer,
    stored_quote.id, btrim(p_customer->>'firstName'), btrim(p_customer->>'lastName'),
    regexp_replace(p_customer->>'phone', '\D', '', 'g'), p_guest_token_hash, p_idempotency_key, p_payload_hash,
    p_accepted_terms_version, now(), p_accepted_lead_time_notice_version,
    case when p_accepted_lead_time_notice_version is null then null else now() end,
    invoice_requested, p_invoice->>'companyName', p_invoice->>'nip',
    case when invoice_requested then coalesce(nullif(p_invoice->>'email',''), lower(p_customer->>'email')) else null end,
    p_invoice#>>'{address,line1}', nullif(p_invoice#>>'{address,line2}',''), p_invoice#>>'{address,postalCode}',
    p_invoice#>>'{address,city}', p_invoice#>>'{address,countryCode}'
  ) returning * into created;

  for item in select value from jsonb_array_elements(stored_quote.quote->'items') loop
    insert into public.order_items (order_id, merchandise_id, name, quantity, unit_price, discount_total, line_total, components)
    values (created.id, item->>'merchandiseId', item->>'name', (item->>'quantity')::integer,
      (item->>'unitPriceGrosze')::integer, (item->>'discountGrosze')::integer,
      (item->>'lineTotalGrosze')::integer, item->'components');
  end loop;
  for item in select value from jsonb_array_elements(stored_quote.quote#>'{giftPromotion,selectedItems}') loop
    insert into public.order_items (order_id, merchandise_id, name, quantity, unit_price, line_total, is_gift)
    values (created.id, item->>'merchandiseId', item->>'name', (item->>'quantity')::integer, 0, 0, true);
  end loop;

  insert into public.order_deliveries (
    order_id, method, price, rule_version, parcel_size, point_id,
    address_line1, address_line2, postal_code, city, country_code
  ) values (
    created.id, stored_quote.delivery_method, (stored_quote.quote#>>'{delivery,priceGrosze}')::integer,
    stored_quote.quote#>>'{delivery,ruleVersion}', stored_quote.quote#>>'{delivery,parcelSize}',
    nullif(p_delivery->>'pointId',''), p_delivery#>>'{address,line1}', nullif(p_delivery#>>'{address,line2}',''),
    p_delivery#>>'{address,postalCode}', p_delivery#>>'{address,city}', p_delivery#>>'{address,countryCode}'
  );
  update public.checkout_quotes set consumed_at = now() where id = stored_quote.id;

  return jsonb_build_object(
    'orderId', created.id::text, 'orderNumber', 'MON-' || lpad(created.order_number::text, 6, '0'),
    'orderDisposition', 'created', 'orderStatus', created.status
  );
end;
$$;

create or replace function public.get_guest_order_status(
  p_guest_token_hash text,
  p_phone text,
  p_request_fingerprint text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  perform private.commerce_rate_limit('status', p_request_fingerprint, 20, interval '10 minutes');
  select jsonb_build_object(
    'orderNumber', 'MON-' || lpad(o.order_number::text, 6, '0'), 'status', o.status,
    'createdAt', o.created_at, 'totalGrosze', o.total, 'currency', o.currency,
    'invoiceRequested', o.invoice_requested,
    'items', (select jsonb_agg(jsonb_build_object(
      'name', i.name, 'quantity', i.quantity, 'unitPriceGrosze', i.unit_price,
      'lineTotalGrosze', i.line_total, 'isGift', i.is_gift
    ) order by i.id) from public.order_items i where i.order_id = o.id),
    'delivery', jsonb_build_object(
      'method', d.method, 'pointId', d.point_id, 'city', d.city, 'priceGrosze', d.price
    )
  ) into result
  from public.orders o join public.order_deliveries d on d.order_id = o.id
  where o.guest_token_hash = p_guest_token_hash
    and o.phone = regexp_replace(p_phone, '\D', '', 'g');
  if result is null then raise exception using errcode = 'P0001', message = 'ORDER_NOT_FOUND'; end if;
  return result;
end;
$$;

revoke execute on function public.create_checkout_quote(jsonb,jsonb,text,text) from public;
revoke execute on function public.finalize_guest_order(uuid,jsonb,jsonb,jsonb,text,text,text,text,text,text) from public;
revoke execute on function public.get_guest_order_status(text,text,text) from public;
revoke execute on function public.create_checkout_quote(jsonb,jsonb,text,text) from anon, authenticated;
revoke execute on function public.finalize_guest_order(uuid,jsonb,jsonb,jsonb,text,text,text,text,text,text) from anon, authenticated;
revoke execute on function public.get_guest_order_status(text,text,text) from anon, authenticated;
grant execute on function public.create_checkout_quote(jsonb,jsonb,text,text) to service_role;
grant execute on function public.finalize_guest_order(uuid,jsonb,jsonb,jsonb,text,text,text,text,text,text) to service_role;
grant execute on function public.get_guest_order_status(text,text,text) to service_role;

revoke execute on function private.commerce_rate_limit(text,text,integer,interval) from public, anon, authenticated;
revoke execute on function private.commerce_build_quote(jsonb,jsonb,text,timestamptz) from public, anon, authenticated;
revoke execute on function private.is_valid_polish_nip(text) from public, anon, authenticated;

comment on function public.finalize_guest_order(uuid,jsonb,jsonb,jsonb,text,text,text,text,text,text) is
  'Controlled anonymous checkout transaction. It validates all input, reprices, rate limits, and exposes no table privileges.';
